import { Octokit } from '@octokit/rest';
import type { Task } from '../planner/types.js';

/**
 * GitHub API 客户端封装
 */
export class GitHubClient {
  private octokit: Octokit;
  private owner: string;
  private repo: string;

  constructor(token: string, owner: string, repo: string) {
    this.octokit = new Octokit({ auth: token });
    this.owner = owner;
    this.repo = repo;
  }

  /**
   * 验证 Token 有效性
   */
  async validate(): Promise<boolean> {
    try {
      const { data } = await this.octokit.users.getAuthenticated();
      return !!data.login;
    } catch {
      return false;
    }
  }

  /**
   * 创建分支
   */
  async createBranch(branchName: string, baseBranch: string = 'main'): Promise<void> {
    const { data: ref } = await this.octokit.git.getRef({
      owner: this.owner,
      repo: this.repo,
      ref: `heads/${baseBranch}`,
    });

    await this.octokit.git.createRef({
      owner: this.owner,
      repo: this.repo,
      ref: `refs/heads/${branchName}`,
      sha: ref.object.sha,
    });
  }

  /**
   * 创建 Pull Request
   */
  async createPR(
    task: Task,
    branchName: string,
    baseBranch: string = 'main'
  ): Promise<{ number: number; url: string }> {
    const { data: pr } = await this.octokit.pulls.create({
      owner: this.owner,
      repo: this.repo,
      title: `[${task.id}] ${task.title}`,
      head: branchName,
      base: baseBranch,
      body: this.generatePRBody(task),
    });

    return { number: pr.number, url: pr.html_url };
  }

  /**
   * 生成 PR 描述
   */
  private generatePRBody(task: Task): string {
    const criteria = task.acceptanceCriteria.map((c) => `- [ ] ${c}`).join('\n');
    return `## ${task.title}

**任务 ID**: ${task.id}

### 验收标准

${criteria}

---
_🤖 Generated by slotht-code-agent_
`;
  }

  /**
   * 添加 PR Reviewer
   */
  async addReviewer(prNumber: number, reviewers: string[]): Promise<void> {
    await this.octokit.pulls.requestReviewers({
      owner: this.owner,
      repo: this.repo,
      pull_number: prNumber,
      reviewers,
    });
  }
}
